### PR TITLE
Fix security hole in GraphQL API

### LINKED ISSUE #55: req.headers.authorization in '/graphql/server.js' Equals "Bearer <token>" - We Only Need "<token>"
`server/graphql/server.js` line 24.

### PR DESCRIPTION
**Pull request by hitochan777**
- Previously you needed to whitelist public GraphQL operations but now you will have to wrap resolver object with `authenticated` middleware to guard it against non-loggedin users. It turned out that `req.body.operationName` does not refer to the query type name but it is literally a operation name.

   For example in the query below, operation name is `login` so even if query type name is `user`, users were able to call it.
  ```graphql
   query login {
      user {
        email
      }
   }
    ```
- GraphQL requests by authenticated users also work with SSR
- Fix a bug of JWT token not properly extracted

Fixes #55

### CODE REVIEW

File: server/graphql/schema.js [hunk 1]
```diff
@@ -31,9 +32,9 @@ const RootQuery = new GraphQLObjectType({
     user: {
       type: UserType,
       args: { id: { type: GraphQLID } },
-      resolve(parent, args) {
+      resolve: authenticated((parent, args) => {
```
Comment (hitochan777) [inline server/graphql/schema.js:35]: Now you need to wrap resolver objects with `authenticated` middleware to prevent unauthenticated users from calling them

**Review by willjw3 — APPROVED** [review]
Awesome! You even wrote some tests!
Looks good to me. I'll merge it and try to break it. :)
